name: CD - Deploy apps.marianialessandro.com

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy apps.marianialessandro.com
    runs-on: ubuntu-latest
    env:
      PUBLIC_API_BASE_URL: https://api.marianialessandro.com/api

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔨 Build apps.marianialessandro.com
        run: npm run build:apps

      - name: 📂 Sync apps via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftp
          port: 21

          local-dir: apps/apps.marianialessandro.com/build/
          server-dir: apps.marianialessandro.com/

          dangerous-clean-slate: false
          log-level: verbose
          timeout: 60000
